FROM mcr.microsoft.com/mssql/server:2022-latest
COPY Chinook_SqlServer_AutoIncrementPKs.sql /home/
COPY create_chinook_sqlserver_autoincrementpks.bash /home/
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=Karkas@Passw0rd
