conn chinook/chinook

ALTER TABLE "Album" MODIFY ("AlbumId" GENERATED ALWAYS AS IDENTITY (START WITH 348));

ALTER TABLE "Artist" MODIFY ("ArtistId" GENERATED ALWAYS AS IDENTITY (START WITH 276));

ALTER TABLE "Customer" MODIFY ("CustomerId" GENERATED ALWAYS AS IDENTITY (START WITH 60));

ALTER TABLE "Employee" MODIFY ("EmployeeId" GENERATED ALWAYS AS IDENTITY (START WITH 9));

commit;
exit;