SET ANSI_NULLS ON
GO --ExecuteThisSql
SET QUOTED_IDENTIFIER ON
GO --ExecuteThisSql
CREATE TABLE [ORNEKLER].[ACIKLAMA](
	[AciklamaKey] [uniqueidentifier] NOT NULL,
	[Aciklama] [varchar](50) NOT NULL,
 CONSTRAINT [PK_ACIKLAMA] PRIMARY KEY CLUSTERED 
(
	[AciklamaKey] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO --ExecuteThisSql

