SET ANSI_NULLS ON
GO --ExecuteThisSql
SET QUOTED_IDENTIFIER ON
GO --ExecuteThisSql
CREATE TABLE [ORNEKLER].[IDENTITY_TINY_INT](
	[IdentityTinyIntKey] [tinyint] IDENTITY(1,1) NOT NULL,
	[Adi] [varchar](50) NULL,
 CONSTRAINT [PK_IDENTITY_TINY_INT] PRIMARY KEY CLUSTERED 
(
	[IdentityTinyIntKey] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO --ExecuteThisSql

