SET ANSI_NULLS ON
GO --ExecuteThisSql
SET QUOTED_IDENTIFIER ON
GO --ExecuteThisSql
CREATE TABLE [ORNEKLER].[CONCURRENCY_ORNEK](
	[ConcurrencyOrnekKey] [uniqueidentifier] NOT NULL CONSTRAINT [DF_CONCURRENCY_ORNEK_ConcurrencyOrnekKey]  DEFAULT (newid()),
	[Adi] [varchar](50) NOT NULL,
	[VersiyonZamani] [timestamp] NOT NULL,
 CONSTRAINT [PK_CONCURRENCY_ORNEK] PRIMARY KEY CLUSTERED 
(
	[ConcurrencyOrnekKey] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO --ExecuteThisSql

