USE KARKAS_ORNEK
GO 
SET ANSI_NULLS ON
GO --ExecuteThisSql
SET QUOTED_IDENTIFIER ON
GO --ExecuteThisSql
CREATE TABLE [ORNEKLER].[DENEME_GUID_IDENTITY](
	[DenemeKey] [uniqueidentifier] NOT NULL CONSTRAINT [DF_DENEME_GUID_IDENTITY_DenemeKey]  DEFAULT (newid()),
	[DenemeNo] [int] IDENTITY(1,1) NOT NULL,
	[DenemeKolon] [varchar](50) NOT NULL,
 CONSTRAINT [PK_DENEME_GUID_IDENTITY] PRIMARY KEY NONCLUSTERED 
(
	[DenemeKey] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO --ExecuteThisSql

