/*******************************************************************************
   Create database
********************************************************************************/
CREATE USER datatypes
IDENTIFIED BY datatypes
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT connect to datatypes;
GRANT resource to datatypes;
GRANT create session TO datatypes;
GRANT create table TO datatypes;
GRANT create view TO datatypes;



conn datatypes/datatypes


/*******************************************************************************
   Create Tables
********************************************************************************/
CREATE TABLE DENEME
(
    "PK_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    "C_INT" INT,
    "C_INTEGER" INTEGER,
    "C_CLOB" CLOB,
    "C_VLOB" VLOB,
    "C_BLOB" BLOG,
    CONSTRAINT PK_Album PRIMARY KEY  ("PK_ID")
);


commit;
exit;
