/*******************************************************************************
   Create database
********************************************************************************/
CREATE USER datatypes
IDENTIFIED BY datatypes
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT connect to datatypes;
GRANT resource to datatypes;
GRANT create session TO datatypes;
GRANT create table TO datatypes;
GRANT create view TO datatypes;



conn datatypes/datatypes


/*******************************************************************************
   Create Tables
********************************************************************************/
CREATE TABLE DENEME
(
    "PK_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    "C_INT" INT,
    "C_INTEGER" INTEGER,
    "C_CLOB" CLOB,
    CONSTRAINT PK_DENEME PRIMARY KEY  ("PK_ID")
);

CREATE TABLE INT_TABLES
(
  PK_ID INTEGER,
  COLUMN_INT       INTEGER                      NOT NULL,
  COLUMN_INTEGER   INTEGER                      NOT NULL,
  COLUMN_SMALLINT  INTEGER                      NOT NULL,
  COLUMN_NUMBER    NUMBER                       NOT NULL,
  COLUMN_DECIMAL   INTEGER                      NOT NULL,
  CONSTRAINT PK_INT_TABLES PRIMARY KEY  ("PK_ID")
)
;


commit;
exit;
