name: deploy-to-nuget

on:
  workflow_dispatch:
  push:
    paths:
      - 'version.txt'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: deploy nuget bash
      shell: bash
      run: ./deploy_nuget_packages.bash
      env:
        KARKAS_NUGET_API_KEY: ${{ secrets.KARKAS_NUGET_API_KEY }}




