name: oracle-datatypes

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["sqlserver-datatypes"]
    branches: [master]
    types: 
      - completed

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: code generate for DataTypes Oracle database and run simple tests
      run: ./Karkas.Examples/TestBash/run_oracle_datatypes.bash
