name: tutorial-sample-blog-console

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: checkout docs/tutorial-sample-blog
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          docs/tutorial-sample-blog
        sparse-checkout-cone-mode: false
    - name: check file
      run: ls -al docs/tutorial-sample-blog
    - name: run create_sample_blog.bash
      run: ./create_sample_blog.bash
      working-directory: docs/tutorial-sample-blog
    - name: Upload the project folder as an artifact
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: sample-blog
        path: docs/tutorial-sample-blog/GeneratedProjects/sample-blog/
        if-no-files-found: error
        include-hidden-files: true
        compression-level: 9
    - name: Output artifact ID
      run:  echo 'Compressed project files could be downloaded from ${{ steps.artifact-upload-step.outputs.artifact-url }}'

