name: tutorial-sample-blog-console

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout docs/tutorial-sample-blog
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          docs/tutorial-sample-blog
        sparse-checkout-cone-mode: false
    - name: check file
      run: ls -al docs/tutorial-sample-blog
    - name: run create_sample_blog.bash
      run: ./create_sample_blog.bash
      working-directory: docs/tutorial-sample-blog
    - name: Upload the zip file as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: upload output file sample-blog.zip
        path: docs/tutorial-sample-blog/GeneratedProjects/sample-blog/sample-blog.zip
        if-no-files-found: error
        include-hidden-files: true



