name: tutorial-sample-blog-console

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install karkas-code-gen
      run: dotnet tool install --global Karkas.CodeGeneration.ConsoleApp
    - name: check karkas-code-gen
      run: karkas-codegen
    - name: checkout karkas-config.json
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          docs/tutorial-sample-blog
        sparse-checkout-cone-mode: false
    - name: check file
      run: ls -al docs/tutorial-sample-blog




